hawkular-cassandra:
  image: hawkular-cassandra:1.3.0-alpha.3
  ports:
    - "7000:7000"
    - "7001:7001"
    - "9042:9042"
    - "9160:9160"

hawkular-services:
  image: hawkular-services:0.0.10
  ports:
    - "8082:8080"
  links:
    - hawkular-cassandra
  environment:
    - HAWKULAR_BACKEND=remote
    - CASSANDRA_NODES=hawkular-cassandra

#hawkular-apm:
#  image: hawkular-apm:0.0.9
#  ports:
#    - "8081:8080"

#hawkular-grafana:
#  image: hawkular-grafana:latest
#  ports:
#    - "3000:3000"
