hawkular-cassandra:
  image: hawkular-cassandra:1.5.0
  environment:
    - CASSANDRA_START_RPC=true
    - MAX_HEAP_SIZE="4G"
  ports:
    - "7000:7000"
    - "7001:7001"
    - "9042:9042"
    - "9160:9160"
#  volumes:
#    - /tmp/opt/hawkular/cassandra:/var/lib/cassandra

hawkular-services:
  image: hawkular-services:0.38.0
  ports:
    - "8080:8080"
    - "8443:8443"
    - "8787:8787"
#  volumes:
#    - /tmp/opt/hawkular/server:/opt/data
  links:
    - hawkular-cassandra
  environment:
    - HAWKULAR_BACKEND=remote
    - CASSANDRA_NODES=hawkular-cassandra
    - HAWKULAR_USER=jdoe
    - HAWKULAR_PASSWORD=password
    - HAWKULAR_AGENT_ENABLE=true
    - HAWKULAR_METRICS_TTL=17
    - LAUNCH_JBOSS_IN_BACKGROUND=true

hawkular-grafana:
  image: hawkular-grafana:1.0.10
  ports:
    - "3000:3000"
  links:
    - hawkular-services
