hawkular-cassandra:
  image: hawkular-cassandra:3.7
  environment:
    - CASSANDRA_START_RPC=true
#  volumes:
#    - /tmp/opt/hawkular/cassandra:/var/lib/cassandra

hawkular-services:
  image: hawkular-services:0.0.11
  ports:
    - "8080:8080"
    - "8443:8443"
    - "8787:8787"
#  volumes:
#    - /tmp/opt/hawkular/server:/opt/data
  links:
    - hawkular-cassandra
  environment:
    - HAWKULAR_BACKEND=remote
    - CASSANDRA_NODES=hawkular-cassandra
    - HAWKULAR_USER=jdoe
    - HAWKULAR_PASSWORD=password
    - HAWKULAR_AGENT_ENABLE=true
    - HAWKULAR_METRICS_TTL=17

#hawkular-apm:
#  image: hawkular-apm:0.0.9
#  ports:
#    - "8081:8080"

#hawkular-grafana:
#  image: hawkular-grafana:0.1
#  ports:
#    - "3000:3000"
