hawkular-cassandra:
  image: hawkular-cassandra:1.3.0-alpha3
  ports:
    - "7000:7000"
    - "7001:7001"
    - "9042:9042"
    - "9160:9160"

hawkular-metrics:
  image: hawkular-metrics:1.3.0-alpha3
  ports:
    - "8080:8080"
    - "8444:8444"
  links:
    - hawkular-cassandra

hawkular-services:
  image: hawkular-services:0.0.9
  links:
    - hawkular-cassandra
  environment:
    - CASSANDRA_NODES=hawkular-cassandra

#hawkular-apm:
#  image: hawkular-apm:0.0.9

